spring:
  application:
    name: Rezension
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/a
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
Jwt:
  secret: 83827348ew7897)#(@Rwuoudyiyfd897*7#(@&890